#!/usr/bin/env python
#-*-coding:utf-8-*-

import sys
from XClient import *
from XComm import *

def main():
    if len(sys.argv)!= 3:
        logInfo("Usage:xrun hostAlias eg:xrun dev cmd")
        printHosts()
        sys.exit(-1)
    #
    alias = sys.argv[1];
    host = getHostByAlias(alias)
    client=XClient(host)
    client.run(sys.argv[2])

if __name__ == '__main__':
    main()